"""empty message

Revision ID: 54c7b1e33572
Revises: cc3a646b9232
Create Date: 2022-04-11 15:39:08.284298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c7b1e33572'
down_revision = 'cc3a646b9232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('userpass', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'userpass')
    # ### end Alembic commands ###
