"""empty message

Revision ID: cc3a646b9232
Revises: e8e0dd88df1e
Create Date: 2022-04-10 11:47:42.128875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc3a646b9232'
down_revision = 'e8e0dd88df1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###
